# main repository to fetch from
repo = "helix-editor/helix"

# the repository's branch
# remote-branch = "master @ 377e36908a15a4fee46a42ecd6cc8f76e171c23b"
remote-branch = "master"

# This is the branch where you will see all result from patchy's work. Set it to any branch you want.
# WARNING: Make sure you do not store any important work on this branch. It will be erased.
local-branch = "patchy"

# List of pull requests which you would like to merge
# TIP: Add comments above pull requests to help yourself understand which PRs do what
pull-requests = [
  # adds file explorer
  "11285",
  # command expansions
  "12527",
  # full screen overlays
  "12311",
  # select around quote
  "12494",
  # open hover documentaton
  "12208",
  # change case of text
  "12043",
  # fix newline insert panic
  "12510 @ 47ce2a8f1600432c94c243af7a5b7949f5bcf06f",
]

patches = ["file-browser-mappings"]
